# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:


{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];


  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];


  fileSystems."/" =
    { device = "/dev/disk/by-uuid/84010c24-2fc7-40e0-907e-af36542bced9";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };


  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/84010c24-2fc7-40e0-907e-af36542bced9";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };


  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/84010c24-2fc7-40e0-907e-af36542bced9";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };


  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7B74-D0ED";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };


  swapDevices = [ ];


  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}