name: Build and Release GNOME ISO

on:
  push:
    tags:
      - "v*.*" # Запуск только при создании тегов вроде v1.0, v2.0
  workflow_dispatch: # Позволяет запускать сборку вручную через сайт

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Дает права на загрузку файлов в Релизы
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v30
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@v8

    - name: Build ISO Image
      run: |
        nix build .#nixosConfigurations.my-iso.config.system.build.isoImage --no-link --print-out-paths > result_path.txt
        echo "ISO_PATH=$(cat result_path.txt)" >> $GITHUB_ENV

    - name: Prepare Artifact
      run: |
        mkdir -p dist
        cp -v ${{ env.ISO_PATH }}/iso/*.iso dist/nixos-steamdeck-custom.iso

    - name: Upload ISO to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/nixos-steamdeck-custom.iso
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
